// Renders the asset table in docs/PRESENTATION_V2_4_PRODUCT_PROOF.md from the registry and manifest.

import { ASSET_REGISTRY_V24 } from "./asset-registry";
import type { PresentationManifestV24 } from "./types";

export const DOCS_PATH_V24 = "docs/PRESENTATION_V2_4_PRODUCT_PROOF.md";
export const DOCS_BLOCK_START = "<!-- product-proof-assets:start -->";
export const DOCS_BLOCK_END = "<!-- product-proof-assets:end -->";

const cell = (text: string) => text.replace(/\|/g, "\\|");

export function renderAssetTableV24(manifest: PresentationManifestV24): string {
  const lines: string[] = [
    `Generated by the capture script from the registry and manifest (captured ${manifest.capturedAt}, commit ${manifest.commit}${manifest.worktreeDirty ? ", dirty worktree" : ""}).`,
    "",
    "| Asset | Use | Route | Region | Image px (2x) | Sub-regions |",
    "| :- | :- | :- | :- | :- | :- |",
  ];
  for (const asset of ASSET_REGISTRY_V24) {
    const entry = manifest.assets[asset.id];
    if (!entry) continue;
    const use = asset.requiredForCore ? "core" : "appendix";
    const size = `${entry.width} x ${entry.height}${entry.viewport.height !== 1080 ? ` (viewport ${entry.viewport.width} x ${entry.viewport.height})` : ""}`;
    lines.push(
      `| \`${asset.id}\` | ${use} | \`${cell(asset.route)}\` | \`${cell(asset.region)}\` | ${size} | ${Object.keys(entry.subRegions).map((name) => `\`${name}\``).join(", ") || "none"} |`,
    );
  }

  const withSetup = ASSET_REGISTRY_V24.filter((asset) => manifest.assets[asset.id] && asset.setup?.length);
  if (withSetup.length > 0) {
    lines.push("", "Setup interactions (client state only, never a database write):", "");
    for (const asset of withSetup) {
      lines.push(`- \`${asset.id}\`: ${(asset.setup ?? []).map((step) => step.describe).join("; ")}.`);
    }
  }

  const blocked = ASSET_REGISTRY_V24.filter((asset) => !manifest.assets[asset.id]);
  if (blocked.length > 0) {
    lines.push("", "Not captured:", "");
    for (const asset of blocked) {
      lines.push(`- \`${asset.id}\`: ${manifest.notCaptured[asset.id] ?? asset.blockedReason ?? "not captured in this run."}`);
    }
  }
  return lines.join("\n");
}

/** Replaces the generated block, or returns null when the markers are missing. */
export function replaceDocsBlockV24(doc: string, block: string): string | null {
  const start = doc.indexOf(DOCS_BLOCK_START);
  const end = doc.indexOf(DOCS_BLOCK_END);
  if (start < 0 || end < start) return null;
  return `${doc.slice(0, start + DOCS_BLOCK_START.length)}\n${block}\n${doc.slice(end)}`;
}
